server:
  port: 8080
logging:
  file:
    name: ./log.log
spring:
  thymeleaf:
    cache: false
    mode: HTML
    encoding: utf-8
    servlet:
      content-type: text/html
  datasource:
    druid:
      url: jdbc:mysql://35.194.220.77:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: root
      stat-view-servlet:
        login-username: admin
        login-password: admin
      initial-size: 0
      max-active: 2
      min-idle: 0
      test-on-borrow: true
      test-on-return: true
      driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  type-aliases-package: com.lien.springboot01.entity
  mapper-locations: classpath:mapper/*.xml
