package com.lien.springboot01.entity;

public class Userinfo extends BaseDomain {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.username
     *
     * @mbg.generated Sat Apr 25 21:52:07 CST 2020
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.age
     *
     * @mbg.generated Sat Apr 25 21:52:07 CST 2020
     */
    private Integer age;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.username
     *
     * @return the value of userinfo.username
     *
     * @mbg.generated Sat Apr 25 21:52:07 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.username
     *
     * @param username the value for userinfo.username
     *
     * @mbg.generated Sat Apr 25 21:52:07 CST 2020
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.age
     *
     * @return the value of userinfo.age
     *
     * @mbg.generated Sat Apr 25 21:52:07 CST 2020
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.age
     *
     * @param age the value for userinfo.age
     *
     * @mbg.generated Sat Apr 25 21:52:07 CST 2020
     */
    public void setAge(Integer age) {
        this.age = age;
    }
}